export const initialWordsOne = [
    { english: 'bus', slovenian: 'avtobus' },
    { english: 'banana', slovenian: 'banana' },
    { english: 'cigarette', slovenian: 'cigareta' },
    { english: 'chocolate', slovenian: 'čokolada' },
    { english: 'money', slovenian: 'denar' },
    { english: 'one', slovenian: 'ena' },
    { english: 'film', slovenian: 'film' },
    { english: 'garage', slovenian: 'garaža' },
    { english: 'hamburger', slovenian: 'hamburger' },
    { english: 'idea', slovenian: 'ideja' },
    { english: 'yogurt', slovenian: 'jogurt' },
    { english: 'coffee', slovenian: 'kava' },
    { english: 'lasagna', slovenian: 'lazanja' },
    { english: 'mom', slovenian: 'mama' },
    { english: 'nose', slovenian: 'nos' },
    { english: 'olive', slovenian: 'oliva' },
    { english: 'pizza', slovenian: 'pica' },
    { english: 'radio', slovenian: 'radio' },
    { english: 'sandwich', slovenian: 'sendvič' },
    { english: 'student', slovenian: 'študent' },
    { english: 'telephone', slovenian: 'telefon' },
    { english: 'clock / hour', slovenian: 'ura' },
    { english: 'water', slovenian: 'voda' },
    { english: 'zebra', slovenian: 'zebra' },
    { english: 'ball', slovenian: 'žoga' },
    { english: 'I', slovenian: 'jaz' },
    { english: 'you (singular informal)', slovenian: 'ti' },
    { english: 'he', slovenian: 'on' },
    { english: 'she', slovenian: 'ona' },
    { english: 'you (plural/formal)', slovenian: 'vi' },
    { english: 'man', slovenian: 'moški' },
    { english: 'woman', slovenian: 'ženska' },
    { english: 'boy', slovenian: 'fant' },
    { english: 'girl', slovenian: 'punca' },
    { english: 'people', slovenian: 'ljudje' },
    { english: 'Good day.', slovenian: 'Dober dan.' },
    { english: 'Good morning.', slovenian: 'Dobro jutro.' },
    { english: 'Good evening.', slovenian: 'Dober večer.' },
    { english: 'Good night.', slovenian: 'Lahko noč.' },
    { english: 'Goodbye.', slovenian: 'Nasvidenje.' },
    { english: 'Hi.', slovenian: 'Živjo.' },
    { english: 'Farewell.', slovenian: 'Adijo.' },
    { english: 'Thank you.', slovenian: 'Hvala.' },
    { english: 'Please / You’re welcome.', slovenian: 'Prosim.' },
    { english: 'Excuse me / I’m sorry.', slovenian: 'Oprostite.' },
    { english: 'Yes.', slovenian: 'Ja.' },
    { english: 'No.', slovenian: 'Ne.' },
    { english: 'I don’t know.', slovenian: 'Ne vem.' },
    { english: 'I don’t understand.', slovenian: 'Ne razumem.' },
    { english: 'Slow down, please.', slovenian: 'Počasi, prosim.' },
    { english: 'Who is this?', slovenian: 'Kdo je to?' },
    { english: 'What is this?', slovenian: 'Kaj je to?' },
    { english: 'This is Mrs. Novak.', slovenian: 'To je gospa Novak.' },
    { english: 'I am Ema Zupan.', slovenian: 'Jaz sem Ema Zupan.' },
    { english: 'Are you Mr. Smole?', slovenian: 'A ste vi gospod Smole?' },
    { english: 'How are you? (singular informal)', slovenian: 'Kako si?' },
    { english: 'How are you? (plural/formal)', slovenian: 'Kako ste?' },
    { english: 'Good.', slovenian: 'Dobro.' },
    { english: 'Bad.', slovenian: 'Slabo.' },
    { english: 'Nice to meet you.', slovenian: 'Me veseli.' },
];

export const initialWordsTwo = [
        { english: 'bus', slovenian: 'avtobus' },
        { english: 'banana', slovenian: 'banana' },
        { english: 'cigarette', slovenian: 'cigareta' },
        { english: 'chocolate', slovenian: 'čokolada' },
        { english: 'money', slovenian: 'denar' },
        { english: 'one', slovenian: 'ena' },
        { english: 'film', slovenian: 'film' },
        { english: 'garage', slovenian: 'garaža' },
        { english: 'hamburger', slovenian: 'hamburger' },
        { english: 'idea', slovenian: 'ideja' },
        { english: 'yogurt', slovenian: 'jogurt' },
        { english: 'coffee', slovenian: 'kava' },
        { english: 'lasagna', slovenian: 'lazanja' },
        { english: 'mom', slovenian: 'mama' },
        { english: 'nose', slovenian: 'nos' },
        { english: 'olive', slovenian: 'oliva' },
        { english: 'pizza', slovenian: 'pica' },
        { english: 'radio', slovenian: 'radio' },
        { english: 'sandwich', slovenian: 'sendvič' },
        { english: 'student', slovenian: 'študent' },
        { english: 'telephone', slovenian: 'telefon' },
        { english: 'clock / hour', slovenian: 'ura' },
        { english: 'water', slovenian: 'voda' },
        { english: 'zebra', slovenian: 'zebra' },
        { english: 'ball', slovenian: 'žoga' },
        { english: 'I', slovenian: 'jaz' },
        { english: 'you (singular informal)', slovenian: 'ti' },
        { english: 'he', slovenian: 'on' },
        { english: 'she', slovenian: 'ona' },
        { english: 'you (plural/formal)', slovenian: 'vi' },
        { english: 'man', slovenian: 'moški' },
        { english: 'woman', slovenian: 'ženska' },
        { english: 'boy', slovenian: 'fant' },
        { english: 'girl', slovenian: 'punca' },
        { english: 'people', slovenian: 'ljudje' },
        { english: 'Good day.', slovenian: 'Dober dan.' },
        { english: 'Good morning.', slovenian: 'Dobro jutro.' },
        { english: 'Good evening.', slovenian: 'Dober večer.' },
        { english: 'Good night.', slovenian: 'Lahko noč.' },
        { english: 'Goodbye.', slovenian: 'Nasvidenje.' },
        { english: 'Hi.', slovenian: 'Živjo.' },
        { english: 'Farewell.', slovenian: 'Adijo.' },
        { english: 'Thank you.', slovenian: 'Hvala.' },
        { english: 'Please / You’re welcome.', slovenian: 'Prosim.' },
        { english: 'Excuse me / I’m sorry.', slovenian: 'Oprostite.' },
        { english: 'Yes.', slovenian: 'Ja.' },
        { english: 'No.', slovenian: 'Ne.' },
        { english: 'I don’t know.', slovenian: 'Ne vem.' },
        { english: 'I don’t understand.', slovenian: 'Ne razumem.' },
        { english: 'Slow down, please.', slovenian: 'Počasi, prosim.' },
        { english: 'Who is this?', slovenian: 'Kdo je to?' },
        { english: 'What is this?', slovenian: 'Kaj je to?' },
        { english: 'This is Mrs. Novak.', slovenian: 'To je gospa Novak.' },
        { english: 'I am Ema Zupan.', slovenian: 'Jaz sem Ema Zupan.' },
        { english: 'Are you Mr. Smole?', slovenian: 'A ste vi gospod Smole?' },
        { english: 'How are you? (singular informal)', slovenian: 'Kako si?' },
        { english: 'How are you? (plural/formal)', slovenian: 'Kako ste?' },
        { english: 'Good.', slovenian: 'Dobro.' },
        { english: 'Bad.', slovenian: 'Slabo.' },
        { english: 'Nice to meet you.', slovenian: 'Me veseli.' },    
        { english: 'mom', slovenian: 'mama' },
        { english: 'nose', slovenian: 'nos' },
        { english: 'olive', slovenian: 'oliva' },
        { english: 'pizza', slovenian: 'pica' },
        { english: 'radio', slovenian: 'radio' },
        { english: 'sandwich', slovenian: 'sendvič' },
        { english: 'student', slovenian: 'študent' },
        { english: 'telephone', slovenian: 'telefon' },
        { english: 'clock', slovenian: 'ura' },
        { english: 'water', slovenian: 'voda' },
        { english: 'zebra', slovenian: 'zebra' },
        { english: 'ball', slovenian: 'žoga' },
        { english: 'mom', slovenian: 'mama' },
        { english: 'father', slovenian: 'oče' },
        { english: 'parents', slovenian: 'starši' },
        { english: 'child', slovenian: 'otrok' },
        { english: 'zero', slovenian: 'nič' },
        { english: 'husband', slovenian: 'mož' },
        { english: 'wife', slovenian: 'žena' },
        { english: 'son', slovenian: 'sin' },
        { english: 'daughter', slovenian: 'hčerka' },
        { english: 'dog', slovenian: 'pes' },
        { english: 'sister', slovenian: 'sestra' },
        { english: 'brother', slovenian: 'brat' },
        { english: 'grandfather', slovenian: 'dedek' },
        { english: 'grandmother', slovenian: 'babica' },
        { english: 'cat', slovenian: 'mačka' },
        { english: 'one', slovenian: 'ena' },
        { english: 'two', slovenian: 'dve' },
        { english: 'three', slovenian: 'tri' },
        { english: 'four', slovenian: 'štiri' },
        { english: 'five', slovenian: 'pet' },
        { english: 'six', slovenian: 'šest' },
        { english: 'seven', slovenian: 'sedem' },
        { english: 'eight', slovenian: 'osem' },
        { english: 'nine', slovenian: 'devet' },
        { english: 'ten', slovenian: 'deset' },
        { english: 'first name', slovenian: 'ime' },
        { english: 'last name', slovenian: 'priimek' },
        { english: 'gender', slovenian: 'spol' },
        { english: 'address', slovenian: 'naslov' },
        { english: 'signature', slovenian: 'podpis' },
        { english: 'country', slovenian: 'država' },
        { english: 'email address', slovenian: 'e-naslov' },
        { english: 'date of birth', slovenian: 'datum rojstva' },
        { english: 'place of birth', slovenian: 'kraj rojstva' },
        { english: 'telephone number', slovenian: 'telefonska številka' },
        { english: 'I am Nika.', slovenian: 'Jaz sem Nika.' },
        { english: 'My last name is Novak.', slovenian: 'Pišem se Novak.' },
        { english: 'I am from Slovenia.', slovenian: 'Sem iz Slovenije.' },
        { english: 'My email is ema@uni.si.', slovenian: 'Moj e-naslov je Ema afna uni pika si.' },
        { english: 'My address is Prešernova ulica 3.', slovenian: 'Moj naslov je Prešernova ulica 3.' },
        { english: 'My phone number is 051 416 260.', slovenian: 'Moja telefonska številka je 051 416 260.' },
        { english: 'How old are you?', slovenian: 'Koliko si star?' },
        { english: 'I am forty-three years old.', slovenian: 'Star sem triinštirideset.' },
        { english: 'I am twenty-five years old.', slovenian: 'Stara sem petindvajset.' },
        { english: 'Can I have your email?', slovenian: 'A mi daš e-naslov?' },
        { english: 'What is your name?', slovenian: 'Kako ti je ime?' },
        { english: 'What is your last name?', slovenian: 'Kako se pišeš?' },
        { english: 'Are you on Facebook?', slovenian: 'A si na Facebooku?' },
        { english: 'Where are you from?', slovenian: 'Od kod si?' },
        { english: 'Peter is from Austria.', slovenian: 'Peter je iz Avstrije.' },
        { english: 'And you?', slovenian: 'In ti?' },
        { english: 'This is my family.', slovenian: 'To je moja družina.' },
        { english: 'This is my brother.', slovenian: 'To je moj brat.' },
        { english: 'I have three children.', slovenian: 'Imam tri otroke.' },
        { english: 'I am not married.', slovenian: 'Nisem poročena.' },
        { english: 'I have no children.', slovenian: 'Nimam otrok.' }
];

export const initialWordsThree = [
    { english: 'bus', slovenian: 'avtobus' },
    { english: 'banana', slovenian: 'banana' },
    { english: 'cigarette', slovenian: 'cigareta' },
    { english: 'chocolate', slovenian: 'čokolada' },
    { english: 'money', slovenian: 'denar' },
    { english: 'one', slovenian: 'ena' },
    { english: 'film', slovenian: 'film' },
    { english: 'garage', slovenian: 'garaža' },
    { english: 'hamburger', slovenian: 'hamburger' },
    { english: 'idea', slovenian: 'ideja' },
    { english: 'yogurt', slovenian: 'jogurt' },
    { english: 'coffee', slovenian: 'kava' },
    { english: 'lasagna', slovenian: 'lazanja' },
    { english: 'mom', slovenian: 'mama' },
    { english: 'nose', slovenian: 'nos' },
    { english: 'olive', slovenian: 'oliva' },
    { english: 'pizza', slovenian: 'pica' },
    { english: 'radio', slovenian: 'radio' },
    { english: 'sandwich', slovenian: 'sendvič' },
    { english: 'student', slovenian: 'študent' },
    { english: 'telephone', slovenian: 'telefon' },
    { english: 'clock / hour', slovenian: 'ura' },
    { english: 'water', slovenian: 'voda' },
    { english: 'zebra', slovenian: 'zebra' },
    { english: 'ball', slovenian: 'žoga' },
    { english: 'I', slovenian: 'jaz' },
    { english: 'you (singular informal)', slovenian: 'ti' },
    { english: 'he', slovenian: 'on' },
    { english: 'she', slovenian: 'ona' },
    { english: 'you (plural/formal)', slovenian: 'vi' },
    { english: 'man', slovenian: 'moški' },
    { english: 'woman', slovenian: 'ženska' },
    { english: 'boy', slovenian: 'fant' },
    { english: 'girl', slovenian: 'punca' },
    { english: 'people', slovenian: 'ljudje' },
    { english: 'Good day.', slovenian: 'Dober dan.' },
    { english: 'Good morning.', slovenian: 'Dobro jutro.' },
    { english: 'Good evening.', slovenian: 'Dober večer.' },
    { english: 'Good night.', slovenian: 'Lahko noč.' },
    { english: 'Goodbye.', slovenian: 'Nasvidenje.' },
    { english: 'Hi.', slovenian: 'Živjo.' },
    { english: 'Farewell.', slovenian: 'Adijo.' },
    { english: 'Thank you.', slovenian: 'Hvala.' },
    { english: 'Please / You’re welcome.', slovenian: 'Prosim.' },
    { english: 'Excuse me / I’m sorry.', slovenian: 'Oprostite.' },
    { english: 'Yes.', slovenian: 'Ja.' },
    { english: 'No.', slovenian: 'Ne.' },
    { english: 'I don’t know.', slovenian: 'Ne vem.' },
    { english: 'I don’t understand.', slovenian: 'Ne razumem.' },
    { english: 'Slow down, please.', slovenian: 'Počasi, prosim.' },
    { english: 'Who is this?', slovenian: 'Kdo je to?' },
    { english: 'What is this?', slovenian: 'Kaj je to?' },
    { english: 'This is Mrs. Novak.', slovenian: 'To je gospa Novak.' },
    { english: 'I am Ema Zupan.', slovenian: 'Jaz sem Ema Zupan.' },
    { english: 'Are you Mr. Smole?', slovenian: 'A ste vi gospod Smole?' },
    { english: 'How are you? (singular informal)', slovenian: 'Kako si?' },
    { english: 'How are you? (plural/formal)', slovenian: 'Kako ste?' },
    { english: 'Good.', slovenian: 'Dobro.' },
    { english: 'Bad.', slovenian: 'Slabo.' },
    { english: 'Nice to meet you.', slovenian: 'Me veseli.' },    
    { english: 'mom', slovenian: 'mama' },
    { english: 'nose', slovenian: 'nos' },
    { english: 'olive', slovenian: 'oliva' },
    { english: 'pizza', slovenian: 'pica' },
    { english: 'radio', slovenian: 'radio' },
    { english: 'sandwich', slovenian: 'sendvič' },
    { english: 'student', slovenian: 'študent' },
    { english: 'telephone', slovenian: 'telefon' },
    { english: 'clock', slovenian: 'ura' },
    { english: 'water', slovenian: 'voda' },
    { english: 'zebra', slovenian: 'zebra' },
    { english: 'ball', slovenian: 'žoga' },
    { english: 'mom', slovenian: 'mama' },
    { english: 'father', slovenian: 'oče' },
    { english: 'parents', slovenian: 'starši' },
    { english: 'child', slovenian: 'otrok' },
    { english: 'zero', slovenian: 'nič' },
    { english: 'husband', slovenian: 'mož' },
    { english: 'wife', slovenian: 'žena' },
    { english: 'son', slovenian: 'sin' },
    { english: 'daughter', slovenian: 'hčerka' },
    { english: 'dog', slovenian: 'pes' },
    { english: 'sister', slovenian: 'sestra' },
    { english: 'brother', slovenian: 'brat' },
    { english: 'grandfather', slovenian: 'dedek' },
    { english: 'grandmother', slovenian: 'babica' },
    { english: 'cat', slovenian: 'mačka' },
    { english: 'one', slovenian: 'ena' },
    { english: 'two', slovenian: 'dve' },
    { english: 'three', slovenian: 'tri' },
    { english: 'four', slovenian: 'štiri' },
    { english: 'five', slovenian: 'pet' },
    { english: 'six', slovenian: 'šest' },
    { english: 'seven', slovenian: 'sedem' },
    { english: 'eight', slovenian: 'osem' },
    { english: 'nine', slovenian: 'devet' },
    { english: 'ten', slovenian: 'deset' },
    { english: 'first name', slovenian: 'ime' },
    { english: 'last name', slovenian: 'priimek' },
    { english: 'gender', slovenian: 'spol' },
    { english: 'address', slovenian: 'naslov' },
    { english: 'signature', slovenian: 'podpis' },
    { english: 'country', slovenian: 'država' },
    { english: 'email address', slovenian: 'e-naslov' },
    { english: 'date of birth', slovenian: 'datum rojstva' },
    { english: 'place of birth', slovenian: 'kraj rojstva' },
    { english: 'telephone number', slovenian: 'telefonska številka' },
    { english: 'I am Nika.', slovenian: 'Jaz sem Nika.' },
    { english: 'My last name is Novak.', slovenian: 'Pišem se Novak.' },
    { english: 'I am from Slovenia.', slovenian: 'Sem iz Slovenije.' },
    { english: 'My email is ema@uni.si.', slovenian: 'Moj e-naslov je Ema afna uni pika si.' },
    { english: 'My address is Prešernova ulica 3.', slovenian: 'Moj naslov je Prešernova ulica 3.' },
    { english: 'My phone number is 051 416 260.', slovenian: 'Moja telefonska številka je 051 416 260.' },
    { english: 'How old are you?', slovenian: 'Koliko si star?' },
    { english: 'I am forty-three years old.', slovenian: 'Star sem triinštirideset.' },
    { english: 'I am twenty-five years old.', slovenian: 'Stara sem petindvajset.' },
    { english: 'Can I have your email?', slovenian: 'A mi daš e-naslov?' },
    { english: 'What is your name?', slovenian: 'Kako ti je ime?' },
    { english: 'What is your last name?', slovenian: 'Kako se pišeš?' },
    { english: 'Are you on Facebook?', slovenian: 'A si na Facebooku?' },
    { english: 'Where are you from?', slovenian: 'Od kod si?' },
    { english: 'Peter is from Austria.', slovenian: 'Peter je iz Avstrije.' },
    { english: 'And you?', slovenian: 'In ti?' },
    { english: 'This is my family.', slovenian: 'To je moja družina.' },
    { english: 'This is my brother.', slovenian: 'To je moj brat.' },
    { english: 'I have three children.', slovenian: 'Imam tri otroke.' },
    { english: 'I am not married.', slovenian: 'Nisem poročena.' },
    { english: 'I have no children.', slovenian: 'Nimam otrok.' },
    { english: 'every day', slovenian: 'vsak dan' },
    { english: 'today', slovenian: 'danes' },
    { english: 'yesterday', slovenian: 'včeraj' },
    { english: 'tomorrow', slovenian: 'jutri' },
    { english: 'never', slovenian: 'nikoli' },
    { english: 'in the morning', slovenian: 'zjutraj' },
    { english: 'in the forenoon', slovenian: 'dopoldne' },
    { english: 'in the afternoon', slovenian: 'popoldne' },
    { english: 'in the evening', slovenian: 'zvečer' },
    { english: 'at night', slovenian: 'ponoči' },
    { english: 'I get up', slovenian: 'vstanem' },
    { english: 'I shower', slovenian: 'tuširam se' },
    { english: 'I go to work', slovenian: 'grem v službo' },
    { english: 'I write', slovenian: 'pišem' },
    { english: 'I go home', slovenian: 'grem domov' },
    { english: 'I cook', slovenian: 'kuham' },
    { english: 'I go to the store', slovenian: 'grem v trgovino' },
    { english: 'I watch TV', slovenian: 'gledam televizijo' },
    { english: 'I listen to music', slovenian: 'poslušam glasbo' },
    { english: 'I go for a walk', slovenian: 'grem na sprehod' },
    { english: 'breakfast', slovenian: 'zajtrk' },
    { english: 'lunch', slovenian: 'kosilo' },
    { english: 'dinner', slovenian: 'večerja' },
    { english: 'I drink', slovenian: 'pijem' },
    { english: 'I eat', slovenian: 'jem' },
    { english: 'Monday', slovenian: 'ponedeljek' },
    { english: 'Tuesday', slovenian: 'torek' },
    { english: 'Wednesday', slovenian: 'sreda' },
    { english: 'Thursday', slovenian: 'četrtek' },
    { english: 'Friday', slovenian: 'petek' },
    { english: 'Saturday', slovenian: 'sobota' },
    { english: 'Sunday', slovenian: 'nedelja' },
    { english: 'I sleep', slovenian: 'spim' },
    { english: 'I read', slovenian: 'berem' },
    { english: 'I rest', slovenian: 'počivam' },
    { english: 'In the morning I get up.', slovenian: 'Zjutraj vstanem.' },
    { english: 'I drink coffee and eat breakfast.', slovenian: 'Pijem kavo in jem zajtrk.' },
    { english: 'At seven I go to work.', slovenian: 'Ob sedmih grem v službo.' },
    { english: 'At three I go home.', slovenian: 'Ob treh grem domov.' },
    { english: 'At one I have lunch.', slovenian: 'Ob enih imam kosilo.' },
    { english: 'In the afternoon I read or rest.', slovenian: 'Popoldne berem ali počivam.' },
    { english: 'In the evening I go on the internet.', slovenian: 'Zvečer grem na internet.' },
    { english: 'At ten I go to sleep.', slovenian: 'Ob desetih grem spat.' },
    { english: 'On Friday I go to the store.', slovenian: 'V petek grem v trgovino.' },
    { english: 'On Saturday I go for a walk.', slovenian: 'V soboto grem na sprehod.' },
    { english: 'What do you like to do?', slovenian: 'Kaj rad delaš?' },
    { english: 'Do you like to read?', slovenian: 'A rada bereš?' },
    { english: 'I like to drink beer.', slovenian: 'Rad pijem pivo.' },
    { english: 'I don’t like to cook.', slovenian: 'Ne maram kuhati.' },
    { english: 'I never drink wine.', slovenian: 'Nikoli ne pijem vina.' },
    { english: 'Today is Monday.', slovenian: 'Danes je ponedeljek.' },
    { english: 'What do you do every day?', slovenian: 'Kaj delaš vsak dan?' },
    { english: 'What are you doing?', slovenian: 'Kaj delaš?' },
    { english: 'Every day I eat breakfast.', slovenian: 'Vsak dan jem zajtrk.' },
    { english: 'Do you cook every day?', slovenian: 'A vsak dan kuhaš?' },
    { english: 'What time is it?', slovenian: 'Koliko je ura?' },
    { english: 'It is four o’clock.', slovenian: 'Ura je štiri.' },
    { english: 'When is dinner?', slovenian: 'Kdaj je večerja?' },
    { english: 'Today I am not going to work.', slovenian: 'Danes ne grem v službo.' },
    { english: 'On Sundays I don’t work.', slovenian: 'Ob nedeljah ne delam.' },
];

export const initialWordsFour = [
    { english: 'bus', slovenian: 'avtobus' },
    { english: 'banana', slovenian: 'banana' },
    { english: 'cigarette', slovenian: 'cigareta' },
    { english: 'chocolate', slovenian: 'čokolada' },
    { english: 'money', slovenian: 'denar' },
    { english: 'one', slovenian: 'ena' },
    { english: 'film', slovenian: 'film' },
    { english: 'garage', slovenian: 'garaža' },
    { english: 'hamburger', slovenian: 'hamburger' },
    { english: 'idea', slovenian: 'ideja' },
    { english: 'yogurt', slovenian: 'jogurt' },
    { english: 'coffee', slovenian: 'kava' },
    { english: 'lasagna', slovenian: 'lazanja' },
    { english: 'mom', slovenian: 'mama' },
    { english: 'nose', slovenian: 'nos' },
    { english: 'olive', slovenian: 'oliva' },
    { english: 'pizza', slovenian: 'pica' },
    { english: 'radio', slovenian: 'radio' },
    { english: 'sandwich', slovenian: 'sendvič' },
    { english: 'student', slovenian: 'študent' },
    { english: 'telephone', slovenian: 'telefon' },
    { english: 'clock / hour', slovenian: 'ura' },
    { english: 'water', slovenian: 'voda' },
    { english: 'zebra', slovenian: 'zebra' },
    { english: 'ball', slovenian: 'žoga' },
    { english: 'I', slovenian: 'jaz' },
    { english: 'you (singular informal)', slovenian: 'ti' },
    { english: 'he', slovenian: 'on' },
    { english: 'she', slovenian: 'ona' },
    { english: 'you (plural/formal)', slovenian: 'vi' },
    { english: 'man', slovenian: 'moški' },
    { english: 'woman', slovenian: 'ženska' },
    { english: 'boy', slovenian: 'fant' },
    { english: 'girl', slovenian: 'punca' },
    { english: 'people', slovenian: 'ljudje' },
    { english: 'Good day.', slovenian: 'Dober dan.' },
    { english: 'Good morning.', slovenian: 'Dobro jutro.' },
    { english: 'Good evening.', slovenian: 'Dober večer.' },
    { english: 'Good night.', slovenian: 'Lahko noč.' },
    { english: 'Goodbye.', slovenian: 'Nasvidenje.' },
    { english: 'Hi.', slovenian: 'Živjo.' },
    { english: 'Farewell.', slovenian: 'Adijo.' },
    { english: 'Thank you.', slovenian: 'Hvala.' },
    { english: 'Please / You’re welcome.', slovenian: 'Prosim.' },
    { english: 'Excuse me / I’m sorry.', slovenian: 'Oprostite.' },
    { english: 'Yes.', slovenian: 'Ja.' },
    { english: 'No.', slovenian: 'Ne.' },
    { english: 'I don’t know.', slovenian: 'Ne vem.' },
    { english: 'I don’t understand.', slovenian: 'Ne razumem.' },
    { english: 'Slow down, please.', slovenian: 'Počasi, prosim.' },
    { english: 'Who is this?', slovenian: 'Kdo je to?' },
    { english: 'What is this?', slovenian: 'Kaj je to?' },
    { english: 'This is Mrs. Novak.', slovenian: 'To je gospa Novak.' },
    { english: 'I am Ema Zupan.', slovenian: 'Jaz sem Ema Zupan.' },
    { english: 'Are you Mr. Smole?', slovenian: 'A ste vi gospod Smole?' },
    { english: 'How are you? (singular informal)', slovenian: 'Kako si?' },
    { english: 'How are you? (plural/formal)', slovenian: 'Kako ste?' },
    { english: 'Good.', slovenian: 'Dobro.' },
    { english: 'Bad.', slovenian: 'Slabo.' },
    { english: 'Nice to meet you.', slovenian: 'Me veseli.' },    
    { english: 'mom', slovenian: 'mama' },
    { english: 'nose', slovenian: 'nos' },
    { english: 'olive', slovenian: 'oliva' },
    { english: 'pizza', slovenian: 'pica' },
    { english: 'radio', slovenian: 'radio' },
    { english: 'sandwich', slovenian: 'sendvič' },
    { english: 'student', slovenian: 'študent' },
    { english: 'telephone', slovenian: 'telefon' },
    { english: 'clock', slovenian: 'ura' },
    { english: 'water', slovenian: 'voda' },
    { english: 'zebra', slovenian: 'zebra' },
    { english: 'ball', slovenian: 'žoga' },
    { english: 'mom', slovenian: 'mama' },
    { english: 'father', slovenian: 'oče' },
    { english: 'parents', slovenian: 'starši' },
    { english: 'child', slovenian: 'otrok' },
    { english: 'zero', slovenian: 'nič' },
    { english: 'husband', slovenian: 'mož' },
    { english: 'wife', slovenian: 'žena' },
    { english: 'son', slovenian: 'sin' },
    { english: 'daughter', slovenian: 'hčerka' },
    { english: 'dog', slovenian: 'pes' },
    { english: 'sister', slovenian: 'sestra' },
    { english: 'brother', slovenian: 'brat' },
    { english: 'grandfather', slovenian: 'dedek' },
    { english: 'grandmother', slovenian: 'babica' },
    { english: 'cat', slovenian: 'mačka' },
    { english: 'one', slovenian: 'ena' },
    { english: 'two', slovenian: 'dve' },
    { english: 'three', slovenian: 'tri' },
    { english: 'four', slovenian: 'štiri' },
    { english: 'five', slovenian: 'pet' },
    { english: 'six', slovenian: 'šest' },
    { english: 'seven', slovenian: 'sedem' },
    { english: 'eight', slovenian: 'osem' },
    { english: 'nine', slovenian: 'devet' },
    { english: 'ten', slovenian: 'deset' },
    { english: 'first name', slovenian: 'ime' },
    { english: 'last name', slovenian: 'priimek' },
    { english: 'gender', slovenian: 'spol' },
    { english: 'address', slovenian: 'naslov' },
    { english: 'signature', slovenian: 'podpis' },
    { english: 'country', slovenian: 'država' },
    { english: 'email address', slovenian: 'e-naslov' },
    { english: 'date of birth', slovenian: 'datum rojstva' },
    { english: 'place of birth', slovenian: 'kraj rojstva' },
    { english: 'telephone number', slovenian: 'telefonska številka' },
    { english: 'I am Nika.', slovenian: 'Jaz sem Nika.' },
    { english: 'My last name is Novak.', slovenian: 'Pišem se Novak.' },
    { english: 'I am from Slovenia.', slovenian: 'Sem iz Slovenije.' },
    { english: 'My email is ema@uni.si.', slovenian: 'Moj e-naslov je Ema afna uni pika si.' },
    { english: 'My address is Prešernova ulica 3.', slovenian: 'Moj naslov je Prešernova ulica 3.' },
    { english: 'My phone number is 051 416 260.', slovenian: 'Moja telefonska številka je 051 416 260.' },
    { english: 'How old are you?', slovenian: 'Koliko si star?' },
    { english: 'I am forty-three years old.', slovenian: 'Star sem triinštirideset.' },
    { english: 'I am twenty-five years old.', slovenian: 'Stara sem petindvajset.' },
    { english: 'Can I have your email?', slovenian: 'A mi daš e-naslov?' },
    { english: 'What is your name?', slovenian: 'Kako ti je ime?' },
    { english: 'What is your last name?', slovenian: 'Kako se pišeš?' },
    { english: 'Are you on Facebook?', slovenian: 'A si na Facebooku?' },
    { english: 'Where are you from?', slovenian: 'Od kod si?' },
    { english: 'Peter is from Austria.', slovenian: 'Peter je iz Avstrije.' },
    { english: 'And you?', slovenian: 'In ti?' },
    { english: 'This is my family.', slovenian: 'To je moja družina.' },
    { english: 'This is my brother.', slovenian: 'To je moj brat.' },
    { english: 'I have three children.', slovenian: 'Imam tri otroke.' },
    { english: 'I am not married.', slovenian: 'Nisem poročena.' },
    { english: 'I have no children.', slovenian: 'Nimam otrok.' },
    { english: 'every day', slovenian: 'vsak dan' },
    { english: 'today', slovenian: 'danes' },
    { english: 'yesterday', slovenian: 'včeraj' },
    { english: 'tomorrow', slovenian: 'jutri' },
    { english: 'never', slovenian: 'nikoli' },
    { english: 'in the morning', slovenian: 'zjutraj' },
    { english: 'in the forenoon', slovenian: 'dopoldne' },
    { english: 'in the afternoon', slovenian: 'popoldne' },
    { english: 'in the evening', slovenian: 'zvečer' },
    { english: 'at night', slovenian: 'ponoči' },
    { english: 'I get up', slovenian: 'vstanem' },
    { english: 'I shower', slovenian: 'tuširam se' },
    { english: 'I go to work', slovenian: 'grem v službo' },
    { english: 'I write', slovenian: 'pišem' },
    { english: 'I go home', slovenian: 'grem domov' },
    { english: 'I cook', slovenian: 'kuham' },
    { english: 'I go to the store', slovenian: 'grem v trgovino' },
    { english: 'I watch TV', slovenian: 'gledam televizijo' },
    { english: 'I listen to music', slovenian: 'poslušam glasbo' },
    { english: 'I go for a walk', slovenian: 'grem na sprehod' },
    { english: 'breakfast', slovenian: 'zajtrk' },
    { english: 'lunch', slovenian: 'kosilo' },
    { english: 'dinner', slovenian: 'večerja' },
    { english: 'I drink', slovenian: 'pijem' },
    { english: 'I eat', slovenian: 'jem' },
    { english: 'Monday', slovenian: 'ponedeljek' },
    { english: 'Tuesday', slovenian: 'torek' },
    { english: 'Wednesday', slovenian: 'sreda' },
    { english: 'Thursday', slovenian: 'četrtek' },
    { english: 'Friday', slovenian: 'petek' },
    { english: 'Saturday', slovenian: 'sobota' },
    { english: 'Sunday', slovenian: 'nedelja' },
    { english: 'I sleep', slovenian: 'spim' },
    { english: 'I read', slovenian: 'berem' },
    { english: 'I rest', slovenian: 'počivam' },
    { english: 'In the morning I get up.', slovenian: 'Zjutraj vstanem.' },
    { english: 'I drink coffee and eat breakfast.', slovenian: 'Pijem kavo in jem zajtrk.' },
    { english: 'At seven I go to work.', slovenian: 'Ob sedmih grem v službo.' },
    { english: 'At three I go home.', slovenian: 'Ob treh grem domov.' },
    { english: 'At one I have lunch.', slovenian: 'Ob enih imam kosilo.' },
    { english: 'In the afternoon I read or rest.', slovenian: 'Popoldne berem ali počivam.' },
    { english: 'In the evening I go on the internet.', slovenian: 'Zvečer grem na internet.' },
    { english: 'At ten I go to sleep.', slovenian: 'Ob desetih grem spat.' },
    { english: 'On Friday I go to the store.', slovenian: 'V petek grem v trgovino.' },
    { english: 'On Saturday I go for a walk.', slovenian: 'V soboto grem na sprehod.' },
    { english: 'What do you like to do?', slovenian: 'Kaj rad delaš?' },
    { english: 'Do you like to read?', slovenian: 'A rada bereš?' },
    { english: 'I like to drink beer.', slovenian: 'Rad pijem pivo.' },
    { english: 'I don’t like to cook.', slovenian: 'Ne maram kuhati.' },
    { english: 'I never drink wine.', slovenian: 'Nikoli ne pijem vina.' },
    { english: 'Today is Monday.', slovenian: 'Danes je ponedeljek.' },
    { english: 'What do you do every day?', slovenian: 'Kaj delaš vsak dan?' },
    { english: 'What are you doing?', slovenian: 'Kaj delaš?' },
    { english: 'Every day I eat breakfast.', slovenian: 'Vsak dan jem zajtrk.' },
    { english: 'Do you cook every day?', slovenian: 'A vsak dan kuhaš?' },
    { english: 'What time is it?', slovenian: 'Koliko je ura?' },
    { english: 'It is four o’clock.', slovenian: 'Ura je štiri.' },
    { english: 'When is dinner?', slovenian: 'Kdaj je večerja?' },
    { english: 'Today I am not going to work.', slovenian: 'Danes ne grem v službo.' },
    { english: 'On Sundays I don’t work.', slovenian: 'Ob nedeljah ne delam.' },
    { english: 'pear', slovenian: 'hruška' },
    { english: 'apple', slovenian: 'jabolko' },
    { english: 'strawberry', slovenian: 'jagoda' },
    { english: 'lemon', slovenian: 'limona' },
    { english: 'orange', slovenian: 'pomaranča' },
    { english: 'carrot', slovenian: 'korenje' },
    { english: 'garlic', slovenian: 'česen' },
    { english: 'potato', slovenian: 'krompir' },
    { english: 'tomato', slovenian: 'paradižnik' },
    { english: 'lettuce', slovenian: 'solata' },
    { english: 'soup', slovenian: 'juha' },
    { english: 'bread', slovenian: 'kruh' },
    { english: 'meat', slovenian: 'meso' },
    { english: 'fish', slovenian: 'riba' },
    { english: 'cheese', slovenian: 'sir' },
    { english: 'tea', slovenian: 'čaj' },
    { english: 'milk', slovenian: 'mleko' },
    { english: 'juice', slovenian: 'sok' },
    { english: 'beer', slovenian: 'pivo' },
    { english: 'wine', slovenian: 'vino' },
    { english: 'expensive', slovenian: 'drag' },
    { english: 'cheap', slovenian: 'poceni' },
    { english: 'hot', slovenian: 'vroč' },
    { english: 'cold', slovenian: 'mrzel' },
    { english: 'good', slovenian: 'dober' },
    { english: 'pizzeria', slovenian: 'picerija' },
    { english: 'restaurant', slovenian: 'restavracija' },
    { english: 'store', slovenian: 'trgovina' },
    { english: 'market', slovenian: 'tržnica' },
    { english: 'bag', slovenian: 'vrečka' },
    { english: 'cash register', slovenian: 'blagajna' },
    { english: 'working hours', slovenian: 'delovni čas' },
    { english: 'open', slovenian: 'odprto' },
    { english: 'closed', slovenian: 'zaprto' },
    { english: 'bill', slovenian: 'račun' },
    { english: 'Excuse me, where is the store?', slovenian: 'Oprostite, kje je trgovina?' },
    { english: 'This, please.', slovenian: 'To, prosim.' },
    { english: 'One salad, please.', slovenian: 'Eno solato, prosim.' },
    { english: 'How much does it cost?', slovenian: 'Koliko stane?' },
    { english: 'Can I order?', slovenian: 'A lahko naročim?' },
    { english: 'What will you have?', slovenian: 'Kaj boste?' },
    { english: 'Where do you have milk?', slovenian: 'Kje imate mleko?' },
    { english: 'What do you have for lunch?', slovenian: 'Kaj imate za kosilo?' },
    { english: 'Menu, please.', slovenian: 'Jedilni list, prosim.' },
    { english: 'Coffee with milk, please.', slovenian: 'Kavo z mlekom, prosim.' },
    { english: 'Will you have anything else?', slovenian: 'A boste še kaj?' },
    { english: 'Bill, please.', slovenian: 'Račun, prosim.' },
    { english: 'Can I pay?', slovenian: 'A lahko plačam?' },
    { english: 'Do you pay in cash or by card?', slovenian: 'A plačate z gotovino ali kartico?' },
    { english: 'Where is the restroom?', slovenian: 'Kje je stranišče?' },
    { english: 'I like to eat meat.', slovenian: 'Rad jem meso.' },
    { english: 'I like to drink tea.', slovenian: 'Rada pijem čaj.' },
    { english: 'I am a vegetarian.', slovenian: 'Sem vegetarijanka.' },
    { english: 'I am allergic to gluten.', slovenian: 'Alergičen sem na gluten.' },
    { english: 'I don’t eat this.', slovenian: 'Tega ne jem.' },
    { english: 'Cheers!', slovenian: 'Na zdravje!' },
    { english: 'Enjoy your meal!', slovenian: 'Dober tek!' },
    { english: 'I am hungry.', slovenian: 'Lačen sem.' },
    { english: 'I am thirsty.', slovenian: 'Žejna sem.' },
    { english: 'The pizza is really good.', slovenian: 'Pica je res dobra.' },
];

export const initialWordsFive = [
    { english: 'bus', slovenian: 'avtobus' },
    { english: 'banana', slovenian: 'banana' },
    { english: 'cigarette', slovenian: 'cigareta' },
    { english: 'chocolate', slovenian: 'čokolada' },
    { english: 'money', slovenian: 'denar' },
    { english: 'one', slovenian: 'ena' },
    { english: 'film', slovenian: 'film' },
    { english: 'garage', slovenian: 'garaža' },
    { english: 'hamburger', slovenian: 'hamburger' },
    { english: 'idea', slovenian: 'ideja' },
    { english: 'yogurt', slovenian: 'jogurt' },
    { english: 'coffee', slovenian: 'kava' },
    { english: 'lasagna', slovenian: 'lazanja' },
    { english: 'mom', slovenian: 'mama' },
    { english: 'nose', slovenian: 'nos' },
    { english: 'olive', slovenian: 'oliva' },
    { english: 'pizza', slovenian: 'pica' },
    { english: 'radio', slovenian: 'radio' },
    { english: 'sandwich', slovenian: 'sendvič' },
    { english: 'student', slovenian: 'študent' },
    { english: 'telephone', slovenian: 'telefon' },
    { english: 'clock / hour', slovenian: 'ura' },
    { english: 'water', slovenian: 'voda' },
    { english: 'zebra', slovenian: 'zebra' },
    { english: 'ball', slovenian: 'žoga' },
    { english: 'I', slovenian: 'jaz' },
    { english: 'you (singular informal)', slovenian: 'ti' },
    { english: 'he', slovenian: 'on' },
    { english: 'she', slovenian: 'ona' },
    { english: 'you (plural/formal)', slovenian: 'vi' },
    { english: 'man', slovenian: 'moški' },
    { english: 'woman', slovenian: 'ženska' },
    { english: 'boy', slovenian: 'fant' },
    { english: 'girl', slovenian: 'punca' },
    { english: 'people', slovenian: 'ljudje' },
    { english: 'Good day.', slovenian: 'Dober dan.' },
    { english: 'Good morning.', slovenian: 'Dobro jutro.' },
    { english: 'Good evening.', slovenian: 'Dober večer.' },
    { english: 'Good night.', slovenian: 'Lahko noč.' },
    { english: 'Goodbye.', slovenian: 'Nasvidenje.' },
    { english: 'Hi.', slovenian: 'Živjo.' },
    { english: 'Farewell.', slovenian: 'Adijo.' },
    { english: 'Thank you.', slovenian: 'Hvala.' },
    { english: 'Please / You’re welcome.', slovenian: 'Prosim.' },
    { english: 'Excuse me / I’m sorry.', slovenian: 'Oprostite.' },
    { english: 'Yes.', slovenian: 'Ja.' },
    { english: 'No.', slovenian: 'Ne.' },
    { english: 'I don’t know.', slovenian: 'Ne vem.' },
    { english: 'I don’t understand.', slovenian: 'Ne razumem.' },
    { english: 'Slow down, please.', slovenian: 'Počasi, prosim.' },
    { english: 'Who is this?', slovenian: 'Kdo je to?' },
    { english: 'What is this?', slovenian: 'Kaj je to?' },
    { english: 'This is Mrs. Novak.', slovenian: 'To je gospa Novak.' },
    { english: 'I am Ema Zupan.', slovenian: 'Jaz sem Ema Zupan.' },
    { english: 'Are you Mr. Smole?', slovenian: 'A ste vi gospod Smole?' },
    { english: 'How are you? (singular informal)', slovenian: 'Kako si?' },
    { english: 'How are you? (plural/formal)', slovenian: 'Kako ste?' },
    { english: 'Good.', slovenian: 'Dobro.' },
    { english: 'Bad.', slovenian: 'Slabo.' },
    { english: 'Nice to meet you.', slovenian: 'Me veseli.' },    
    { english: 'mom', slovenian: 'mama' },
    { english: 'nose', slovenian: 'nos' },
    { english: 'olive', slovenian: 'oliva' },
    { english: 'pizza', slovenian: 'pica' },
    { english: 'radio', slovenian: 'radio' },
    { english: 'sandwich', slovenian: 'sendvič' },
    { english: 'student', slovenian: 'študent' },
    { english: 'telephone', slovenian: 'telefon' },
    { english: 'clock', slovenian: 'ura' },
    { english: 'water', slovenian: 'voda' },
    { english: 'zebra', slovenian: 'zebra' },
    { english: 'ball', slovenian: 'žoga' },
    { english: 'mom', slovenian: 'mama' },
    { english: 'father', slovenian: 'oče' },
    { english: 'parents', slovenian: 'starši' },
    { english: 'child', slovenian: 'otrok' },
    { english: 'zero', slovenian: 'nič' },
    { english: 'husband', slovenian: 'mož' },
    { english: 'wife', slovenian: 'žena' },
    { english: 'son', slovenian: 'sin' },
    { english: 'daughter', slovenian: 'hčerka' },
    { english: 'dog', slovenian: 'pes' },
    { english: 'sister', slovenian: 'sestra' },
    { english: 'brother', slovenian: 'brat' },
    { english: 'grandfather', slovenian: 'dedek' },
    { english: 'grandmother', slovenian: 'babica' },
    { english: 'cat', slovenian: 'mačka' },
    { english: 'one', slovenian: 'ena' },
    { english: 'two', slovenian: 'dve' },
    { english: 'three', slovenian: 'tri' },
    { english: 'four', slovenian: 'štiri' },
    { english: 'five', slovenian: 'pet' },
    { english: 'six', slovenian: 'šest' },
    { english: 'seven', slovenian: 'sedem' },
    { english: 'eight', slovenian: 'osem' },
    { english: 'nine', slovenian: 'devet' },
    { english: 'ten', slovenian: 'deset' },
    { english: 'first name', slovenian: 'ime' },
    { english: 'last name', slovenian: 'priimek' },
    { english: 'gender', slovenian: 'spol' },
    { english: 'address', slovenian: 'naslov' },
    { english: 'signature', slovenian: 'podpis' },
    { english: 'country', slovenian: 'država' },
    { english: 'email address', slovenian: 'e-naslov' },
    { english: 'date of birth', slovenian: 'datum rojstva' },
    { english: 'place of birth', slovenian: 'kraj rojstva' },
    { english: 'telephone number', slovenian: 'telefonska številka' },
    { english: 'I am Nika.', slovenian: 'Jaz sem Nika.' },
    { english: 'My last name is Novak.', slovenian: 'Pišem se Novak.' },
    { english: 'I am from Slovenia.', slovenian: 'Sem iz Slovenije.' },
    { english: 'My email is ema@uni.si.', slovenian: 'Moj e-naslov je Ema afna uni pika si.' },
    { english: 'My address is Prešernova ulica 3.', slovenian: 'Moj naslov je Prešernova ulica 3.' },
    { english: 'My phone number is 051 416 260.', slovenian: 'Moja telefonska številka je 051 416 260.' },
    { english: 'How old are you?', slovenian: 'Koliko si star?' },
    { english: 'I am forty-three years old.', slovenian: 'Star sem triinštirideset.' },
    { english: 'I am twenty-five years old.', slovenian: 'Stara sem petindvajset.' },
    { english: 'Can I have your email?', slovenian: 'A mi daš e-naslov?' },
    { english: 'What is your name?', slovenian: 'Kako ti je ime?' },
    { english: 'What is your last name?', slovenian: 'Kako se pišeš?' },
    { english: 'Are you on Facebook?', slovenian: 'A si na Facebooku?' },
    { english: 'Where are you from?', slovenian: 'Od kod si?' },
    { english: 'Peter is from Austria.', slovenian: 'Peter je iz Avstrije.' },
    { english: 'And you?', slovenian: 'In ti?' },
    { english: 'This is my family.', slovenian: 'To je moja družina.' },
    { english: 'This is my brother.', slovenian: 'To je moj brat.' },
    { english: 'I have three children.', slovenian: 'Imam tri otroke.' },
    { english: 'I am not married.', slovenian: 'Nisem poročena.' },
    { english: 'I have no children.', slovenian: 'Nimam otrok.' },
    { english: 'every day', slovenian: 'vsak dan' },
    { english: 'today', slovenian: 'danes' },
    { english: 'yesterday', slovenian: 'včeraj' },
    { english: 'tomorrow', slovenian: 'jutri' },
    { english: 'never', slovenian: 'nikoli' },
    { english: 'in the morning', slovenian: 'zjutraj' },
    { english: 'in the forenoon', slovenian: 'dopoldne' },
    { english: 'in the afternoon', slovenian: 'popoldne' },
    { english: 'in the evening', slovenian: 'zvečer' },
    { english: 'at night', slovenian: 'ponoči' },
    { english: 'I get up', slovenian: 'vstanem' },
    { english: 'I shower', slovenian: 'tuširam se' },
    { english: 'I go to work', slovenian: 'grem v službo' },
    { english: 'I write', slovenian: 'pišem' },
    { english: 'I go home', slovenian: 'grem domov' },
    { english: 'I cook', slovenian: 'kuham' },
    { english: 'I go to the store', slovenian: 'grem v trgovino' },
    { english: 'I watch TV', slovenian: 'gledam televizijo' },
    { english: 'I listen to music', slovenian: 'poslušam glasbo' },
    { english: 'I go for a walk', slovenian: 'grem na sprehod' },
    { english: 'breakfast', slovenian: 'zajtrk' },
    { english: 'lunch', slovenian: 'kosilo' },
    { english: 'dinner', slovenian: 'večerja' },
    { english: 'I drink', slovenian: 'pijem' },
    { english: 'I eat', slovenian: 'jem' },
    { english: 'Monday', slovenian: 'ponedeljek' },
    { english: 'Tuesday', slovenian: 'torek' },
    { english: 'Wednesday', slovenian: 'sreda' },
    { english: 'Thursday', slovenian: 'četrtek' },
    { english: 'Friday', slovenian: 'petek' },
    { english: 'Saturday', slovenian: 'sobota' },
    { english: 'Sunday', slovenian: 'nedelja' },
    { english: 'I sleep', slovenian: 'spim' },
    { english: 'I read', slovenian: 'berem' },
    { english: 'I rest', slovenian: 'počivam' },
    { english: 'In the morning I get up.', slovenian: 'Zjutraj vstanem.' },
    { english: 'I drink coffee and eat breakfast.', slovenian: 'Pijem kavo in jem zajtrk.' },
    { english: 'At seven I go to work.', slovenian: 'Ob sedmih grem v službo.' },
    { english: 'At three I go home.', slovenian: 'Ob treh grem domov.' },
    { english: 'At one I have lunch.', slovenian: 'Ob enih imam kosilo.' },
    { english: 'In the afternoon I read or rest.', slovenian: 'Popoldne berem ali počivam.' },
    { english: 'In the evening I go on the internet.', slovenian: 'Zvečer grem na internet.' },
    { english: 'At ten I go to sleep.', slovenian: 'Ob desetih grem spat.' },
    { english: 'On Friday I go to the store.', slovenian: 'V petek grem v trgovino.' },
    { english: 'On Saturday I go for a walk.', slovenian: 'V soboto grem na sprehod.' },
    { english: 'What do you like to do?', slovenian: 'Kaj rad delaš?' },
    { english: 'Do you like to read?', slovenian: 'A rada bereš?' },
    { english: 'I like to drink beer.', slovenian: 'Rad pijem pivo.' },
    { english: 'I don’t like to cook.', slovenian: 'Ne maram kuhati.' },
    { english: 'I never drink wine.', slovenian: 'Nikoli ne pijem vina.' },
    { english: 'Today is Monday.', slovenian: 'Danes je ponedeljek.' },
    { english: 'What do you do every day?', slovenian: 'Kaj delaš vsak dan?' },
    { english: 'What are you doing?', slovenian: 'Kaj delaš?' },
    { english: 'Every day I eat breakfast.', slovenian: 'Vsak dan jem zajtrk.' },
    { english: 'Do you cook every day?', slovenian: 'A vsak dan kuhaš?' },
    { english: 'What time is it?', slovenian: 'Koliko je ura?' },
    { english: 'It is four o’clock.', slovenian: 'Ura je štiri.' },
    { english: 'When is dinner?', slovenian: 'Kdaj je večerja?' },
    { english: 'Today I am not going to work.', slovenian: 'Danes ne grem v službo.' },
    { english: 'On Sundays I don’t work.', slovenian: 'Ob nedeljah ne delam.' },
    { english: 'pear', slovenian: 'hruška' },
    { english: 'apple', slovenian: 'jabolko' },
    { english: 'strawberry', slovenian: 'jagoda' },
    { english: 'lemon', slovenian: 'limona' },
    { english: 'orange', slovenian: 'pomaranča' },
    { english: 'carrot', slovenian: 'korenje' },
    { english: 'garlic', slovenian: 'česen' },
    { english: 'potato', slovenian: 'krompir' },
    { english: 'tomato', slovenian: 'paradižnik' },
    { english: 'lettuce', slovenian: 'solata' },
    { english: 'soup', slovenian: 'juha' },
    { english: 'bread', slovenian: 'kruh' },
    { english: 'meat', slovenian: 'meso' },
    { english: 'fish', slovenian: 'riba' },
    { english: 'cheese', slovenian: 'sir' },
    { english: 'tea', slovenian: 'čaj' },
    { english: 'milk', slovenian: 'mleko' },
    { english: 'juice', slovenian: 'sok' },
    { english: 'beer', slovenian: 'pivo' },
    { english: 'wine', slovenian: 'vino' },
    { english: 'expensive', slovenian: 'drag' },
    { english: 'cheap', slovenian: 'poceni' },
    { english: 'hot', slovenian: 'vroč' },
    { english: 'cold', slovenian: 'mrzel' },
    { english: 'good', slovenian: 'dober' },
    { english: 'pizzeria', slovenian: 'picerija' },
    { english: 'restaurant', slovenian: 'restavracija' },
    { english: 'store', slovenian: 'trgovina' },
    { english: 'market', slovenian: 'tržnica' },
    { english: 'bag', slovenian: 'vrečka' },
    { english: 'cash register', slovenian: 'blagajna' },
    { english: 'working hours', slovenian: 'delovni čas' },
    { english: 'open', slovenian: 'odprto' },
    { english: 'closed', slovenian: 'zaprto' },
    { english: 'bill', slovenian: 'račun' },
    { english: 'Excuse me, where is the store?', slovenian: 'Oprostite, kje je trgovina?' },
    { english: 'This, please.', slovenian: 'To, prosim.' },
    { english: 'One salad, please.', slovenian: 'Eno solato, prosim.' },
    { english: 'How much does it cost?', slovenian: 'Koliko stane?' },
    { english: 'Can I order?', slovenian: 'A lahko naročim?' },
    { english: 'What will you have?', slovenian: 'Kaj boste?' },
    { english: 'Where do you have milk?', slovenian: 'Kje imate mleko?' },
    { english: 'What do you have for lunch?', slovenian: 'Kaj imate za kosilo?' },
    { english: 'Menu, please.', slovenian: 'Jedilni list, prosim.' },
    { english: 'Coffee with milk, please.', slovenian: 'Kavo z mlekom, prosim.' },
    { english: 'Will you have anything else?', slovenian: 'A boste še kaj?' },
    { english: 'Bill, please.', slovenian: 'Račun, prosim.' },
    { english: 'Can I pay?', slovenian: 'A lahko plačam?' },
    { english: 'Do you pay in cash or by card?', slovenian: 'A plačate z gotovino ali kartico?' },
    { english: 'Where is the restroom?', slovenian: 'Kje je stranišče?' },
    { english: 'I like to eat meat.', slovenian: 'Rad jem meso.' },
    { english: 'I like to drink tea.', slovenian: 'Rada pijem čaj.' },
    { english: 'I am a vegetarian.', slovenian: 'Sem vegetarijanka.' },
    { english: 'I am allergic to gluten.', slovenian: 'Alergičen sem na gluten.' },
    { english: 'I don’t eat this.', slovenian: 'Tega ne jem.' },
    { english: 'Cheers!', slovenian: 'Na zdravje!' },
    { english: 'Enjoy your meal!', slovenian: 'Dober tek!' },
    { english: 'I am hungry.', slovenian: 'Lačen sem.' },
    { english: 'I am thirsty.', slovenian: 'Žejna sem.' },
    { english: 'The pizza is really good.', slovenian: 'Pica je res dobra.' },
    { english: 'professor (male)', slovenian: 'profesor' },
    { english: 'professor (female)', slovenian: 'profesorica' },
    { english: 'student (male)', slovenian: 'študent' },
    { english: 'student (female)', slovenian: 'študentka' },
    { english: 'office', slovenian: 'kabinet' },
    { english: 'economics', slovenian: 'ekonomija' },
    { english: 'law', slovenian: 'pravo' },
    { english: 'medicine', slovenian: 'medicina' },
    { english: 'journalism', slovenian: 'novinarstvo' },
    { english: 'computer science', slovenian: 'računalništvo' },
    { english: 'application form', slovenian: 'prijavnica' },
    { english: 'enrollment confirmation', slovenian: 'potrdilo o vpisu' },
    { english: 'office hours', slovenian: 'govorilne ure' },
    { english: 'notice', slovenian: 'obvestilo' },
    { english: 'scholarship', slovenian: 'štipendija' },
    { english: 'timetable', slovenian: 'urnik' },
    { english: 'lecture', slovenian: 'predavanje' },
    { english: 'exam', slovenian: 'izpit' },
    { english: 'credit points', slovenian: 'kreditne točke' },
    { english: 'semester', slovenian: 'semester' },
    { english: 'student dorm', slovenian: 'študentski dom' },
    { english: 'student ID', slovenian: 'študentska izkaznica' },
    { english: 'student meal voucher', slovenian: 'študentski bon' },
    { english: 'student discount', slovenian: 'študentski popust' },
    { english: 'student service', slovenian: 'študentski servis' },
    { english: 'library', slovenian: 'knjižnica' },
    { english: 'lecture hall', slovenian: 'predavalnica' },
    { english: 'laboratory', slovenian: 'laboratorij' },
    { english: 'reading room', slovenian: 'čitalnica' },
    { english: 'secretariat', slovenian: 'tajništvo' },
    { english: 'party', slovenian: 'žur' },
    { english: 'in love', slovenian: 'zaljubljen' },
    { english: 'drunk', slovenian: 'pijan' },
    { english: 'sleepy', slovenian: 'zaspan' },
    { english: 'condom', slovenian: 'kondom' },
    { english: 'I am a student.', slovenian: 'Jaz sem študent.' },
    { english: 'She is a student.', slovenian: 'Ona je študentka.' },
    { english: 'What are you studying?', slovenian: 'Kaj študiraš?' },
    { english: 'I am studying economics.', slovenian: 'Študiram ekonomijo.' },
    { english: 'Good day, professor.', slovenian: 'Dober dan, gospod profesor.' },
    { english: 'The lecture is at eleven.', slovenian: 'Predavanje je ob enajstih.' },
    { english: 'The lecture is in lecture hall four.', slovenian: 'Predavanje je v predavalnici štiri.' },
    { english: 'Where is the secretariat?', slovenian: 'Kje je tajništvo?' },
    { english: 'Office hours are at one o’clock.', slovenian: 'Govorilne ure so ob enih.' },
    { english: 'The lecture today is cancelled.', slovenian: 'Predavanje danes odpade.' },
    { english: 'The exam is on Wednesday.', slovenian: 'Izpit je v sredo.' },
    { english: 'When do we have the exam?', slovenian: 'Kdaj imamo izpit?' },
    { english: 'What are you studying?', slovenian: 'Kaj se učiš?' },
    { english: 'Did you pass the exam?', slovenian: 'A si naredil izpit?' },
    { english: 'I am in the first year.', slovenian: 'Hodim v prvi letnik.' },
    { english: 'Which bus goes to the university?', slovenian: 'Kateri avtobus gre do faksa?' },
    { english: 'I am going to the lecture.', slovenian: 'Grem na predavanje.' },
    { english: 'I live in the student dorm.', slovenian: 'Živim v študentskem domu.' },
    { english: 'Student menu, please.', slovenian: 'Študentski meni, prosim.' },
    { english: 'Do you have a student ID?', slovenian: 'A imaš študentsko izkaznico?' },
    { english: 'I have a roommate.', slovenian: 'Imam cimra.' },
    { english: 'Are you going to the party?', slovenian: 'A greš na žur?' },
    { english: 'I like you.', slovenian: 'Všeč si mi.' },
    { english: 'Are you going for a beer?', slovenian: 'A greš na pivo?' },
    { english: 'I have a hangover.', slovenian: 'Imam mačka.' },
];
